export const UPDATE_EDITOR_STATE = 'UPDATE_EDITOR_STATE';

export const AUTOSAVE_DOCUMENT = 'AUTOSAVE_DOCUMENT';
export const FETCH_DOCUMENT = 'FETCH_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
