export const BATCH_UPDATE_EDITOR_STATE = 'BATCH_UPDATE_EDITOR_STATE';
export const ITERATIVE_UPDATE_EDITOR_STATE = 'ITERATIVE_UPDATE_EDITOR_STATE';

export const AUTOSAVE_DOCUMENT = 'AUTOSAVE_DOCUMENT';
export const FETCH_DOCUMENT = 'FETCH_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const UPDATE_DOCUMENT_TITLE = 'UPDATE_DOCUMENT_TITLE';
